include: package:pedantic/analysis_options.yaml
#
analyzer:
  exclude:
    - integration_test/**
#  strong-mode:
#    implicit-casts: false
#
linter:
  rules:
    omit_local_variable_types: false
    test_types_in_equals: false
      - camel_case_extensions