name: BrandFarm
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line
  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.1.1
  bloc: ^6.1.1
  firebase_auth: ^0.18.4+1
  equatable: ^1.2.5
  cloud_firestore: ^0.14.4
  font_awesome_flutter: ^8.11.0
  rxdart: ^0.25.0
  animated_text_kit: ^3.1.0
  adaptive_breakpoints: ^0.0.4
  google_fonts: ^1.1.1
  http: ^0.12.2
  flutter_launcher_icons: ^0.8.1
  xml2json: ^4.4.0
  badges: ^1.1.6
#  intl: ^0.16.1
  date_format: ^1.0.9
  animations: ^1.1.2
  scrollable_positioned_list: ^0.1.8
  flutter_speed_dial: ^1.2.5
  flutter_svg: ^0.19.2+1
  multi_image_picker: ^4.6.1


dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2





flutter:
  assets:
    - assets/
    - assets/weather_image/
    - assets/svg_icon/
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
    - family:  BrandFarmIcons
      fonts:
        - asset: assets/icons/setting_icon.ttf
    - family: Weather
      fonts:
        - asset: assets/fonts/Weather/Weather.ttf
    - family: AppleSDGothicNeo
      fonts:
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoL.ttf
          weight: 300
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoR.ttf
          weight: 400
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoM.ttf
          weight: 500
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoB.ttf
          weight: 700
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoEB.ttf
          weight: 800