/// Flutter icons Weather
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Weather
///      fonts:
///       - asset: fonts/Weather.ttf
///
/// 
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
///
import 'package:flutter/widgets.dart';

class Weather {
  Weather._();

  static const _kFontFam = 'Weather';
  static const String _kFontPkg = null;

  static const IconData snow_heavy_inv = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow_heavy = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clouds = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hail_inv = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hail = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_sun = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_moon = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clouds_flash = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun_inv = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_inv = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_sun_inv = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_moon_inv = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain_inv = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_inv = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clouds_flash_alt = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
